### ISSUE TITLE
413 Request Entity Too Large with mirror-registry 2.0.3

### ISSUE THREAD

**Issue by apodhrad** [quay/mirror-registry#179]
When pushing big images to quay installed by mirror-registry 2.0.3 I'm getting this error
```
413 Request Entity Too Large
```

Note that this is working with mirror-registry 1.3.5. I will try also other versions.

**Comment by HammerMeetNail** [comment]
Hey @apodhrad, What is the size of the size of the image? Are you able to share it so we can try to recreate?

**Comment by LiZhang19817** [comment]
@apodhrad We tried to reproduce this issue as you mentioned, but when pushing image with large layer size "9.4GB", can't reproduce this issue, is it possible to share the image to confirm.
```
[centos@ip-10-0-1-4 ~]$ ./mirror-registry --version

   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat
 Build, Store, and Distribute your Containers

mirror-registry version v2.0.3

[centos@ip-10-0-1-4 ~]$ podman push quayomr.qe.devcluster.openshift.com:8443/quay/test123 --tls-verify=false --creds quay:***
Getting image source signatures
Copying blob 2653d992f4ef done   | 
Copying blob 637a3c7a75fa [===>----------------------------------] 1.1GiB / 9.4GiB | 260.1 MiB/s

[centos@ip-10-0-1-4 ~]$ podman push quayomr.qe.devcluster.openshift.com:8443/quay/test123 --tls-verify=false --creds quay:***
Getting image source signatures
Copying blob 2653d992f4ef done   | 
Copying blob 637a3c7a75fa done   | 
Copying config 76e8b2c5c2 done   | 
Writing manifest to image destination
```

**Comment by apodhrad** [comment]
Hi @LiZhang19817 I hit exactly the same error.
Unfortunately, today with a fresh install I was not able reproduce it :(

**Comment by LiZhang19817** [comment]
@apodhrad Is it possible to share your test image then we can see if it's the same issue.

**Comment by lohbe** [comment]
I'm getting the same error as well, attempting to mirror OCP 4.17.14 distribution via disk-to-mirror.

```
2025/02/14 12:43:06  [INFO]   : Mirroring is ongoing. No errors.
 ✓ 97/199 : (19s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:50…
 ✗ 98/199 : (23s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1b…
 ✗ 99/199 : (23s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:75…
 ✗ 100/199 : (23s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a…
101/199 : (23s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1ca6b6104dd90…
 ✗ 102/199 : (23s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5…
 ✓ 103/199 : (19s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1…
 ✗ 104/199 : (23s) quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e…
2025/02/14 12:43:29  [INFO]   : 👋 Goodbye, thank you for using oc-mirror
2025/02/14 12:43:29  [ERROR]  : writing blob: uploading layer chunked: StatusCode: 413, "<html>\r\n<head><title>413 Request Entity Too Large<..."
```

Using quay from `mirror-registry` :

```
$ podman ps -a
CONTAINER ID  IMAGE                                         COMMAND     CREATED       STATUS       PORTS                                       NAMES
8876e15ebc19  registry.access.redhat.com/ubi8/pause:8.10-5  infinity    47 hours ago
  Up 47 hours  0.0.0.0:8443->8443/tcp                      fe354a9444ff-infra
7c512f1d98b3  registry.redhat.io/rhel8/redis-6:1-190        run-redis   47 hours ago  Up 47 hours  0.0.0.0:8443->8443/tcp, 6379/tcp            quay-redis
1d85257f80f0  registry.redhat.io/quay/quay-rhel8:v3.12.5    registry    47 hours ago
  Up 47 hours  0.0.0.0:8443->8443/tcp, 7443/tcp, 8080/tcp  quay-app
```

`imageset-config.yml`

```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.17 
      minVersion: 4.17.14
      maxVersion: 4.17.14
    graph: true 
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17 
      packages: 
       - name: node-observability-operator
  additionalImages: 
   - name: registry.redhat.io/ubi8/ubi:latest
   - name: registry.redhat.io/ubi9/ubi@sha256:20f695d2a91352d4eaa25107535126727b5945bff38ed36a3e59590f495046f0
```

oc-mirror v2 used:

```
  oc mirror --v2 -c imageset-config.yml file://{{local_cache}}
  oc mirror --v2 -c imageset-config.yml --from file://{{local_cache}} docker://mirror.ocp.lan:8443 --dest-tls-verify=false
```
